spring:
  application:
    name: portfolio-spring
  datasource:
    url: jdbc:mariadb://localhost:3306/portfolio-db
    username: portfoliodb
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
server:
  address: 127.0.0.1
  port: 8080
  servlet:
    context-path: /api
